# Workflow for building and deploying a GitSite repo to GitHub Pages

name: Build and Deploy tutorial.ijoy.store

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install GitSite
        run: npm install gitsite-cli -g
      - name: Build with GitSite
        run:
          # set output dir to '_site' for pages jobs:
          gitsite-cli build -o _site
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
